import type { Tab, StarConfig } from "./types";

// Navigation tabs

export const TABS: Tab[] = [
  {
    id: "web",
    title: "Web Engineering",
    description:
      "Fast, scalable, SEO-ready web applications built for real-world usage. Designed for performance, maintainability, and long-term growth.",
  },
  {
    id: "ui",
    title: "UI / UX Design",
    description:
      "Design systems, UI/UX strategy, and product design that feel intuitive, consistent, and delightful for users.",
  },
  {
    id: "product",
    title: "Product Development",
    description:
      "End-to-end product development: MVPs, iteration, scaling, and feature roadmaps for growth-focused products.",
  },
  {
    id: "erp",
    title: "Enterprise & ERP Systems",
    description:
      "Complex ERP systems, workflows, and automation for enterprise operations and logistics.",
  },
];

// Star field positions 

export const STAR_POSITIONS: StarConfig[] = [
  {
    top: "8%",
    left: "12%",
    size: 1.2,
    opacity: 0.18,
    duration: 3.2,
    delay: 0.0,
  },
  {
    top: "22%",
    left: "74%",
    size: 1.6,
    opacity: 0.22,
    duration: 4.5,
    delay: 0.8,
  },
  {
    top: "41%",
    left: "38%",
    size: 0.9,
    opacity: 0.12,
    duration: 2.8,
    delay: 1.4,
  },
  {
    top: "55%",
    left: "88%",
    size: 1.4,
    opacity: 0.2,
    duration: 5.1,
    delay: 0.3,
  },
  {
    top: "68%",
    left: "18%",
    size: 1.0,
    opacity: 0.15,
    duration: 3.8,
    delay: 2.0,
  },
  {
    top: "82%",
    left: "62%",
    size: 1.7,
    opacity: 0.24,
    duration: 4.2,
    delay: 1.1,
  },
  {
    top: "14%",
    left: "52%",
    size: 1.1,
    opacity: 0.16,
    duration: 3.5,
    delay: 0.6,
  },
  {
    top: "35%",
    left: "5%",
    size: 1.3,
    opacity: 0.19,
    duration: 4.8,
    delay: 1.7,
  },
  {
    top: "72%",
    left: "44%",
    size: 0.8,
    opacity: 0.11,
    duration: 2.6,
    delay: 2.4,
  },
  {
    top: "90%",
    left: "82%",
    size: 1.5,
    opacity: 0.21,
    duration: 3.9,
    delay: 0.4,
  },
  {
    top: "5%",
    left: "90%",
    size: 1.0,
    opacity: 0.14,
    duration: 5.3,
    delay: 1.9,
  },
  {
    top: "48%",
    left: "70%",
    size: 1.2,
    opacity: 0.17,
    duration: 4.0,
    delay: 0.9,
  },
  {
    top: "28%",
    left: "28%",
    size: 0.9,
    opacity: 0.13,
    duration: 3.1,
    delay: 2.2,
  },
  {
    top: "60%",
    left: "92%",
    size: 1.6,
    opacity: 0.23,
    duration: 4.6,
    delay: 0.2,
  },
  {
    top: "95%",
    left: "35%",
    size: 1.1,
    opacity: 0.16,
    duration: 3.7,
    delay: 1.5,
  },
  {
    top: "18%",
    left: "6%",
    size: 1.4,
    opacity: 0.2,
    duration: 5.0,
    delay: 0.7,
  },
  {
    top: "75%",
    left: "56%",
    size: 0.8,
    opacity: 0.12,
    duration: 2.9,
    delay: 2.8,
  },
  {
    top: "32%",
    left: "82%",
    size: 1.3,
    opacity: 0.18,
    duration: 4.3,
    delay: 1.2,
  },
  {
    top: "50%",
    left: "22%",
    size: 1.0,
    opacity: 0.15,
    duration: 3.4,
    delay: 0.5,
  },
  {
    top: "88%",
    left: "10%",
    size: 1.5,
    opacity: 0.22,
    duration: 4.9,
    delay: 1.6,
  },
  {
    top: "12%",
    left: "40%",
    size: 0.9,
    opacity: 0.13,
    duration: 3.0,
    delay: 2.1,
  },
  {
    top: "64%",
    left: "76%",
    size: 1.2,
    opacity: 0.17,
    duration: 4.4,
    delay: 0.3,
  },
  {
    top: "38%",
    left: "58%",
    size: 1.6,
    opacity: 0.21,
    duration: 5.2,
    delay: 1.8,
  },
  {
    top: "78%",
    left: "30%",
    size: 1.1,
    opacity: 0.16,
    duration: 3.6,
    delay: 2.5,
  },
];
